[theme]
    base="light"
    font="Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap, sans-serif"
    primaryColor = '#6F4DFA'
    backgroundColor = '#FFFFFF'
    secondaryBackgroundColor = '#FAFAFA'
    textColor = '#0F0035'
    hoverPrimary = '#5a3fd9'
    linkColor = '#6F4DFA'
    showSidebarBorder = true
    baseFontSize = 16
    headingFontSize =  [
        "2rem", # h1
        "1.75rem", # h2
        "1.5rem", # h3
        "1.25rem", # h4
        "1rem", # h5 
        "0.875rem", # h6 
    ]

    [sidebar]
        baseFontSize = 12
        backgroundColor = '#FAFAFA'
        textColor = '#0F0035'
        borderColor = '#E2E8F0'
        headingFontSize =  [
            "1.25rem", # h1
            "1.125rem", # h2
            "1rem", # h3
            "0.875rem", # h4
            "0.75rem", # h5
            "0.625rem", # h6
        ]

[browser]
    gatherUsageStats = false
[server]
    fileWatcherType = "auto"
    runOnSave = true
