# Central style configuration
[colors]
primaryColor = '#6F4DFA'
backgroundColor = '#FAFAFA'
secondaryBackgroundColor = '#FAFAFA'
hover_primary = '#5a3fd9'
bg = '#FAFAFA'
fg = '#0F0035'
accent_bg = '#f3f2fa'
border_gray = '#E2E8F0'
warning_bg = '#FFF0D9'
warning_border = '#FF9D00'

[multiselect]
wrapper_margin = '1rem 0'
tag_padding = '4px 8px'
tag_border = '#6F4DFA'
option_bg = '#FAFAFA'
option_hover_bg = '#E2E8F0'
option_selected_bg = '#6F4DFA'
option_selected_fg = '#FFFFFF'

[slider]
max_width = '400px'

[paths]
themes_csv = 'data/themes.csv'
